# Generated by Django 5.2 on 2025-04-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Book_name', models.CharField(max_length=100)),
                ('Book_code', models.IntegerField()),
                ('Phone_Number', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('MRP', models.IntegerField()),
            ],
        ),
    ]
